#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:2.0.50727.6400
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



public partial class SupermercadoDB : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertProdutos(Produtos instance);
  partial void UpdateProdutos(Produtos instance);
  partial void DeleteProdutos(Produtos instance);
  partial void InsertSupermercado(Supermercado instance);
  partial void UpdateSupermercado(Supermercado instance);
  partial void DeleteSupermercado(Supermercado instance);
  #endregion
	
	public SupermercadoDB() :
      base(@"isostore:/countries.sdf")
	{		
	}
	
//	public SupermercadoDB(System.Data.IDbConnection connection) : 
//			base(connection, mappingSource)
//	{
//		OnCreated();
//	}
	
//	public SupermercadoDB(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
//			base(connection, mappingSource)
//	{
//		OnCreated();
//	}
	
//	public SupermercadoDB(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
//			base(connection, mappingSource)
//	{
//		OnCreated();
//	}
	
	public System.Data.Linq.Table<PrecoProduto> PrecoProduto
	{
		get
		{
			return this.GetTable<PrecoProduto>();
		}
	}	
	public System.Data.Linq.Table<Produtos> Produtos
	{
		get
		{
			return this.GetTable<Produtos>();
		}
	}	
	public System.Data.Linq.Table<Supermercado> Supermercado
	{
		get
		{
			return this.GetTable<Supermercado>();
		}
	}
}

[Table()]
public partial class PrecoProduto
{
	
	private long _Supermercado_id;	
	private long _Produtos_id;	
	private double _Preco;
	
	public PrecoProduto()
	{
	}
	
	[Column(Storage="_Supermercado_id", DbType="BigInt NOT NULL")]
	public long Supermercado_id
	{
		get
		{
			return this._Supermercado_id;
		}
		set
		{
			if ((this._Supermercado_id != value))
			{
				this._Supermercado_id = value;
			}
		}
	}
	
	[Column(Storage="_Produtos_id", DbType="BigInt NOT NULL")]
	public long Produtos_id
	{
		get
		{
			return this._Produtos_id;
		}
		set
		{
			if ((this._Produtos_id != value))
			{
				this._Produtos_id = value;
			}
		}
	}
	
	[Column(Storage="_Preco", DbType="Float NOT NULL")]
	public double Preco
	{
		get
		{
			return this._Preco;
		}
		set
		{
			if ((this._Preco != value))
			{
				this._Preco = value;
			}
		}
	}
}

[Table()]
public partial class Produtos : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);	
	private long _Id;	
	private string _Nome;	
	private string _CodBarras;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnCodBarrasChanging(string value);
    partial void OnCodBarrasChanged();
    #endregion
	
	public Produtos()
	{
		OnCreated();
	}
	
	[Column(Name="id", Storage="_Id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
	public long Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[Column(Storage="_Nome", DbType="NVarChar(500)")]
	public string Nome
	{
		get
		{
			return this._Nome;
		}
		set
		{
			if ((this._Nome != value))
			{
				this.OnNomeChanging(value);
				this.SendPropertyChanging();
				this._Nome = value;
				this.SendPropertyChanged("Nome");
				this.OnNomeChanged();
			}
		}
	}
	
	[Column(Storage="_CodBarras", DbType="NVarChar(500)")]
	public string CodBarras
	{
		get
		{
			return this._CodBarras;
		}
		set
		{
			if ((this._CodBarras != value))
			{
				this.OnCodBarrasChanging(value);
				this.SendPropertyChanging();
				this._CodBarras = value;
				this.SendPropertyChanged("CodBarras");
				this.OnCodBarrasChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[Table()]
public partial class Supermercado : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);	
	private long _Id;	
	private string _Nome;	
	private string _Endereco;	
	private System.Nullable<long> _Numero;	
	private string _Bairro;	
	private string _Cidade;	
	private string _Estado;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(long value);
    partial void OnIdChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnEnderecoChanging(string value);
    partial void OnEnderecoChanged();
    partial void OnNumeroChanging(System.Nullable<long> value);
    partial void OnNumeroChanged();
    partial void OnBairroChanging(string value);
    partial void OnBairroChanged();
    partial void OnCidadeChanging(string value);
    partial void OnCidadeChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    #endregion
	
	public Supermercado()
	{
		OnCreated();
	}
	
	[Column(Name="id", Storage="_Id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
	public long Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[Column(Storage="_Nome", DbType="NVarChar(500)")]
	public string Nome
	{
		get
		{
			return this._Nome;
		}
		set
		{
			if ((this._Nome != value))
			{
				this.OnNomeChanging(value);
				this.SendPropertyChanging();
				this._Nome = value;
				this.SendPropertyChanged("Nome");
				this.OnNomeChanged();
			}
		}
	}
	
	[Column(Storage="_Endereco", DbType="NVarChar(500)")]
	public string Endereco
	{
		get
		{
			return this._Endereco;
		}
		set
		{
			if ((this._Endereco != value))
			{
				this.OnEnderecoChanging(value);
				this.SendPropertyChanging();
				this._Endereco = value;
				this.SendPropertyChanged("Endereco");
				this.OnEnderecoChanged();
			}
		}
	}
	
	[Column(Storage="_Numero", DbType="BigInt")]
	public System.Nullable<long> Numero
	{
		get
		{
			return this._Numero;
		}
		set
		{
			if ((this._Numero != value))
			{
				this.OnNumeroChanging(value);
				this.SendPropertyChanging();
				this._Numero = value;
				this.SendPropertyChanged("Numero");
				this.OnNumeroChanged();
			}
		}
	}
	
	[Column(Storage="_Bairro", DbType="NVarChar(500)")]
	public string Bairro
	{
		get
		{
			return this._Bairro;
		}
		set
		{
			if ((this._Bairro != value))
			{
				this.OnBairroChanging(value);
				this.SendPropertyChanging();
				this._Bairro = value;
				this.SendPropertyChanged("Bairro");
				this.OnBairroChanged();
			}
		}
	}
	
	[Column(Storage="_Cidade", DbType="NVarChar(500)")]
	public string Cidade
	{
		get
		{
			return this._Cidade;
		}
		set
		{
			if ((this._Cidade != value))
			{
				this.OnCidadeChanging(value);
				this.SendPropertyChanging();
				this._Cidade = value;
				this.SendPropertyChanged("Cidade");
				this.OnCidadeChanged();
			}
		}
	}
	
	[Column(Storage="_Estado", DbType="NVarChar(2)")]
	public string Estado
	{
		get
		{
			return this._Estado;
		}
		set
		{
			if ((this._Estado != value))
			{
				this.OnEstadoChanging(value);
				this.SendPropertyChanging();
				this._Estado = value;
				this.SendPropertyChanged("Estado");
				this.OnEstadoChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}


#pragma warning restore 1591
